name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        echo "Building React app..."
        npm run build

        echo "Transferring build directory to EC2 instance..."
        scp -r ./build ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo cp -r /tmp/build /var/www/html/'
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo rm -rf /tmp/build/'

        echo "Removing local build directory..."
        rm -rf build

        echo "Deployment completed successfully."
      env:
        EC2_USER: ec2-user
